### ISSUE TITLE
Highlighting lost after changing file type to .md

### ISSUE THREAD

**Issue by EricEWeir** [lervag/wiki.vim#238]
I added `let g:wiki_filetypes = ['md', 'wiki']` to my `.vimrc`. Does `wiki-ft.vim`work only with `.wiki` extent?

My `.vimrc` follows:

```vim
set encoding=utf-8
set fileencoding=utf-8
set fileformats=unix,dos,mac
set guifont=Menlo:h14

set wrap
set linebreak
set display=lastline
set backup

set clipboard=unnamed

set laststatus=2
set statusline=\ %F\ %r\ %l\ %c\ %y
set mousemodel=popup

set spell spelllang=en_us
set spellfile=~/.vim/spell/en.utf-8.add ~/.vim/spell/en.utf-8.add.spl

let mapleader = ","

noremap <Up> gk
noremap k gk
noremap <Down> gj
noremap j gj
noremap ^ g^
noremap $ g$
inoremap jj <ESC>
nnoremap <Leader>be :%s@^\(\s*\)\(=\+\)\s\+\(.*\)\s\+\2\%(\s*\)$@\=submatch(1).

let g:notes_directories = ['~/notes/']
let g:notes_suffix = '.txt'

let g:wiki_filetypes = ['md', 'wiki']
let g:wiki_link_extension = ['.md']
let g:wiki_journal = {
          \ 'name': 'journal',
          \ 'frequency': 'daily',
          \ 'date_format': {
          \   'daily' : '%y-%m-%d',
          \   'weekly' : '%y_w%V',
          \   'monthly' : '%y_m%m',
          \ },
          \ 'index_use_journal_scheme': v:true,
          \}
let g:wiki_root = '~/wiki/'

let g:wiki_write_on_nav = 1

let g:session_autoload = 'prompt'
let g:session_lock_enabled = 0

autocmd BufRead,BufNewFile *.txt set ft=markdown
```

**Comment by EricEWeir** [comment]
Thanks, Karl. Enjoy your vacation. Hope it’s not your last one this year.

**Comment by lervag** [comment]
> Thanks, Karl. Enjoy your vacation. Hope it’s not your last one this year.

I also have some vacation left for Christmas holidays :)

----

Now, to the issue. Would you find it more convenient if all of your Wiki files were Markdown formatted and had the `.md` extension? If so, then I would propose that you instead install and configure a Markdown plugin and use that. It would be better, I think, than to force the more minimal wiki-ft.vim filetype on Markdown files.

If you already have too many `.wiki` files and therefore want to keep the wiki-ft.vim for these, then you could still benefit from installing a Markdown plugin.

I would suggest that you install [vim-markdown](https://github.com/preservim/vim-markdown). It has a lot of options for configuration; as for most things, I do recommend you read the docs. But some options that I personally like are these:

```vim
" vim-markdown has it's own mapping for following links: "ge"
" wiki.vim will still work, of course, if it is enabled!
let g:vim_markdown_follow_anchor = 1
let g:vim_markdown_no_extensions_in_markdown = 1

let g:vim_markdown_frontmatter = 1
let g:vim_markdown_toml_frontmatter = 1
let g:vim_markdown_new_list_item_indent = 2
let g:vim_markdown_conceal = 2
let g:vim_markdown_conceal_code_blocks = 0
let g:vim_markdown_math = 1
let g:vim_markdown_strikethrough = 1
```

**Comment by EricEWeir** [comment]
Thanks, Karl. Welcome back.

I did experiment a little while you were gone. I tried vim’s native `markdown`. (Is that Tim Pope’s `markdown-vim`?) Wasn’t satisfied with it, but didn’t make notes. I installed `vim-markdown`. Didn’t do any configuration. Didn’t make notes with it either. Still have it. 

So, yes, I would like to do as you suggested. I copied your settings to my `.vimrc`. Added a couple settings of my own. And commented out those of yours I didn’t understand or didn’t think I would need.

I’m getting linking, but not folding or concealing. If I do CR on a word I get “Error detected while processing function wiki#link#follow.” And “Wrong variable type for =.” I suspect those have to with the wiki.vim settings in my .vimrc.

On another note I finally figured out the path to the cloud for my mobile devices. Found it exploring iVim directories with netrw. It just adds `~/privatevar/mobile` to the path I tried previously. Don’t understand why the iVim folks didn’t point it out to me.

***
set encoding=utf-8
set fileencoding=utf-8
set fileformats=unix,dos,mac
set guifont=Menlo:h14

set wrap
set linebreak
set display=lastline
set backup

set clipboard=unnamed

set laststatus=2
set statusline=\ %F\ %r\ %l\ %c\ %y
set mousemodel=popup

set spell spelllang=en_us


let mapleader = ","

noremap <Up> gk
noremap k gk
noremap <Down> gj
noremap j gj
noremap ^ g^
noremap $ g$
inoremap jj <ESC>
nnoremap <Leader>be :%s@^\(\s*\)\(=\+\)\s\+\(.*\)\s\+\2\%(\s*\)$@\=submatch(1).

let g:vim_markdown_follow_anchor = 1
let g:vim_markdown_no_extensions_in_markdown = 1
let g:vim_markdown_new_list_item_indent = 0
let g:vim_markdown_conceal = 2
let g:vim_markdown_folding_level = 6 
let g:vim_markdown_autowrote = 1
autocmd BufRead,BufNewFile *.txt set ft=markdown

"let g:vim_markdown_frontmatter = 1
"let g:vim_markdown_toml_frontmatter = 1
"let g:vim_markdown_conceal_code_blocks = 0
"let g:vim_markdown_math = 1
"let g:vim_markdown_strikethrough = 1

"let g:notes_directories = ['~/library/mobile documents/com~apple~CloudDocs/vimfiles/notes/']
let g:notes_directories = ['~/notes/']
let g:notes_suffix = '.txt'

"let g:wiki_root = '~/library/mobile documents/com~apple~CloudDocs/vimfiles/vimwiki/'
"let g:wiki_root = '~/vimwiki/'

"let g:wiki_root = '~/private/var/mobile/library/Mobile Documents/com~apple~CloudDocs/vimfiles/wiki/'
let g:wiki_root = '~/wiki/'
let g:wiki_filetypes = ['md']
let g:wiki_link_extension = ['.md']
let g:wiki_link_target_type = ['md'] 
let g:wiki_write_on_nav = 1
let g:wiki_journal = {
          \ 'name': 'journal',
          \ 'frequency': 'daily',
          \ 'date_format': {
          \   'daily' : '%y-%m-%d',
          \   'weekly' : '%y_w%V',
          \   'monthly' : '%y_m%m',
          \ },
          \ 'index_use_journal_scheme': v:true,
          \}
let g:session_autoload = 'prompt'
let g:session_lock_enabled = 0

**Comment by lervag** [comment]
> Thanks, Karl. Welcome back.

Thanks :)

> I did experiment a little while you were gone. I tried vim’s native `markdown`. (Is that Tim Pope’s `markdown-vim`?)

Yes, I believe that's correct.

> Wasn’t satisfied with it, but didn’t make notes. I installed `vim-markdown`. Didn’t do any configuration. Didn’t make notes with it either. Still have it.

Notice that these plugins only affect how Vim/neovim behaves when you open Markdown files with the `.md` extension. So, if you choose to use Markdown format and the `.md` extension, then you need to use a Markdown plugin like one of these. As I mentioned, you _can_ use wiki-ft.vim, but I slightly discourage that because wiki-ft.vim does not properly adhere to any Markdown _standard_.

> I’m getting linking, but not folding or concealing. If I do CR on a word I get “Error detected while processing function wiki#link#follow.” And “Wrong variable type for =.” I suspect those have to with the wiki.vim settings in my .vimrc.

To understand this error message, it would also be useful to see the word on which you are pressing `<cr>` and its context.

> On another note I finally figured out the path to the cloud for my mobile devices. Found it exploring iVim directories with netrw. It just adds `~/privatevar/mobile` to the path I tried previously. Don’t understand why the iVim folks didn’t point it out to me.

Ah, nice! Happy to hear it!

Here are some comments to parts of your vimrc file (I've removed things I'm not commenting).

```viml
" I assume you mean _autowrite?
let g:vim_markdown_autowrote = 1

" Why do you want this? If you are writing Markdown in .txt files, why not just
" give them the .md extension?
autocmd BufRead,BufNewFile *.txt set ft=markdown

" This implies that you are, in fact, relying on the Markdown extension. So,
" wiki-ft.vim is currently unused.
let g:wiki_filetypes = ['md']

" This should be a string, not a list!
"let g:wiki_link_extension = ['.md']
let g:wiki_link_extension = '.md'

" Again, this should be a string, not a list!
"let g:wiki_link_target_type = ['md']
let g:wiki_link_target_type = 'md'

" You don't need to specify keys you are not changing, so this can be
" simplified:
"let g:wiki_journal = {
"          \ 'name': 'journal',
"          \ 'frequency': 'daily',
"          \ 'date_format': {
"          \   'daily' : '%y-%m-%d',
"          \   'weekly' : '%y_w%V',
"          \   'monthly' : '%y_m%m',
"          \ },
"          \ 'index_use_journal_scheme': v:true,
"          \}
let g:wiki_journal = {
          \ 'date_format': {
          \   'daily' : '%y-%m-%d',
          \   'weekly' : '%y_w%V',
          \   'monthly' : '%y_m%m',
          \ },
          \}
```

Notice that I propose some fixes/changes where I've kept your version in a comment and my suggestion below uncommented.

**Comment by EricEWeir** [comment]
> Notice that these plugins only affect how Vim/neovim behaves when you open Markdown files with the `.md` extension. So, if you choose to use Markdown format and the `.md` extension, then you need to use a Markdown plugin like one of these. As I mentioned, you _can_ use wiki-ft.vim, but I slightly discourage that because wiki-ft.vim does not properly adhere to any Markdown _standard_.

I had disabled `wiki-ft.vim`. I will delete it.

> > I’m getting linking, but not folding or concealing. If I do CR on a word I get “Error detected while processing function wiki#link#follow.” And “Wrong variable type for =.” I suspect those have to with the wiki.vim settings in my .vimrc.

> To understand this error message, it would also be useful to see the word on which you are pressing `<cr>` and its context.

In rush at the moment. I’ll get back to you with an example and context first thing tomorrow.

> Here are some comments to parts of your vimrc file (I've removed things I'm not commenting).
> 
> " Why do you want this? If you are writing Markdown in .txt files, why not just
> " give them the .md extension?
> autocmd BufRead,BufNewFile *.txt set ft=markdown

It was used by another plugin, `vim-notes`. I’m not gonna keep it. Doesn’t add anything. 
> 
> " This implies that you are, in fact, relying on the Markdown extension. So,
> " wiki-ft.vim is currently unused.

Yes, it's currently disabled. I’ll delete it.

> " This should be a string, not a list!
> "let g:wiki_link_extension = ['.md']
> let g:wiki_link_extension = '.md'
> 
> " Again, this should be a string, not a list!
> "let g:wiki_link_target_type = ['md']
> let g:wiki_link_target_type = 'md'

Don’t under stand “string” vs “list”. But I see the change that needs to be made. I made it.

> ```
> " You don't need to specify keys you are not changing, so this can be
> " simplified:
> "let g:wiki_journal = {
> "          \ 'name': 'journal',
> "          \ 'frequency': 'daily',
> "          \ 'date_format': {
> "          \   'daily' : '%y-%m-%d',
> "          \   'weekly' : '%y_w%V',
> "          \   'monthly' : '%y_m%m',
> "          \ },
> "          \ 'index_use_journal_scheme': v:true,
> "          \}
> let g:wiki_journal = {
>           \ 'date_format': {
>           \   'daily' : '%y-%m-%d',
>           \   'weekly' : '%y_w%V',
>           \   'monthly' : '%y_m%m',
>           \ },
>           \}
> ```

I’ve made the change.

There are some vim-markdown options that I might want to use but not sure I understand. I’ll post about em later.

Thanks much for the followup. When I don’t have explicit instructions I’m often flying blind.

**Comment by EricEWeir** [comment]
Hitting CR on text now produces a markdown style link. Is it possible to have both markdown and wiki style links, e.g., maybe to toggle between them?

**Comment by lervag** [comment]
> Hitting CR on text now produces a markdown style link.

Does it mean the issue is resolved?

> Is it possible to have both markdown and wiki style links, e.g., maybe to toggle between them?

Yes, there's a mapping to do that. By default, it is mapped to `<leader>wf` (leader is comma on your end, I think).

> Don’t understand “string” vs “list”. But I see the change that needs to be made. I made it.

String and List are different variable _types_. A string is text, that is, a sequence of characters. A list is a, well, a list of things. Each thing can be a different object. You can read more about these things with `:help variables`, as well as `:help List` and `:help String`. The reference can probably be somewhat confusing, but I think the first parts of `:help variables` can be at least somewhat enlightening.

**Comment by EricEWeir** [comment]
> > Hitting CR on text now produces a markdown style link.

> Does it mean the issue is resolved?

Insofar as I get markdown links, yes. There is an issue regarding linking in zettelkasten that makes me think wiki-styles links may be more appropriate. Can’t be real clear at the moment. 

I think it has to do with the fact that for zettelkasten purposes, with conceal set what you want to be displayed is the number of the note(s) linked to. 

It may be that in naming new notes with the zettelkasten number, and in searching for existing notes you search on the number, the markdown style will work. I need more experience.

> > Is it possible to have both markdown and wiki style links, e.g., maybe to toggle between them?

> Yes, there's a mapping to do that. By default, it is mapped to `<leader>wf` (leader is comma on your end, I think).

Great. Thanks. I’ll check it out.

> > Don’t understand “string” vs “list”. But I see the change that needs to be made. I made it.

> String and List are different variable _types_. A string is text, that is, a sequence of characters. A list is a, well, a list of things. Each thing can be a different object. You can read more about these things with `:help variables`, as well as `:help List` and `:help String`. The reference can probably be somewhat confusing, but I think the first parts of `:help variables` can be at least somewhat enlightening.

Thanks for the suggestions. (A contribution to my education in vim.) I’ll check them out.

**Comment by lervag** [comment]
> > Does it mean the issue is resolved?
> 
> Insofar as I get markdown links, yes.

Great, then I'll close this issue.

> There is an issue regarding linking in zettelkasten that makes me think wiki-styles links may be more appropriate. Can’t be real clear at the moment.

Feel free to open a new issue if/when you are able to clearly state this issue.

**Comment by EricEWeir** [comment]
Still have a couple issues with markdown: (1) Folding is not working or working strangely. (2) Conceal is not working at all.

The following lines are a note I created to test markdown folding and concealing. In the note they don’t quite  display as they do here. The difference is the “italic” appears italicized but with markdown coding displayed as here. Same with “bold.”

The weird thing about folding is that it doesn’t work on the first three lines with hash marks but does work on the bottom three lines, which have no code for folding.
```
# link 
## link link link 
### link link link
```
```
_italic_
**bold**
[linking](linking.md)
```
Here’s my updated.vimrc:
***

set encoding=utf-8
set fileencoding=utf-8
set fileformats=unix,dos,mac
set guifont=Menlo:h14

set wrap
set linebreak
set display=lastline
set backup

set clipboard=unnamed

set laststatus=2
set statusline=\ %F\ %r\ %l\ %c\ %y
set mousemodel=popup

set spell spelllang=en_us

let mapleader = ","

noremap <Up> gk
noremap k gk
noremap <Down> gj
noremap j gj
noremap ^ g^
noremap $ g$
inoremap jj <ESC>
nnoremap <Leader>be :%s@^\(\s*\)\(=\+\)\s\+\(.*\)\s\+\2\%(\s*\)$@\=submatch(1).

"set foldenable 
let g:vim_markdown_follow_anchor = 1
let g:vim_markdown_no_extensions_in_markdown = 1
let g:vim_markdown_new_list_item_indent = 0
let g:vim_markdown_conceal = 2
let g:vim_markdown_folding_level = 6 
let g:vim_markdown_autowrite = 1
let g:vim_markdown_strikethrough = 1

"let g:wiki_root = '~/library/mobile documents/com~apple~CloudDocs/vimfiles/vimwiki/'
"let g:wiki_root = '~/vimwiki/'

let g:wiki_root = '~/private/var/mobile/library/Mobile Documents/com~apple~CloudDocs/vimfiles/wiki/'
"let g:wiki_root = '~/wiki/'
let g:wiki_filetypes = ['md']
let g:wiki_link_extension = '.md'
let g:wiki_link_target_type = 'md' 
let g:wiki_write_on_nav = 1
let g:wiki_journal = {
          \ 'date_format': {
          \   'daily' : '%y-%m-%d',
          \   'weekly' : '%y_w%V',
          \   'monthly' : '%y_m%m',
          \ },
          \}
let g:session_autoload = 'prompt'
let g:session_lock_enabled = 0

**Comment by lervag** [comment]
> Still have a couple issues with markdown: (1) Folding is not working or working strangely. (2) Conceal is not working at all.

Strange. Can you report the output of the following commands after you've opened one of your notes?

* `:verb set foldmethod`
* `:verb set foldexpr`
* `:verb set filetype`
* `:verb set conceallevel`
* `:verb set concealcursor`

Also, can you do `:version` and check that the output contains `+conceal`?

> The following lines are a note I created to test markdown folding and concealing. In the note they don’t quite display as they do here.

Notice that github flavored markdown is not the same as more "standard" Markdown. Further, notice that there is really no _proper_ standard for Markdown. There are a lot of flavors. These are some references I find useful that display some of the variance:

* [John Gruber's Markdown specs](https://daringfireball.net/projects/markdown/)
* [CommonMark](http://commonmark.org/)
* [Pandoc's Markdown](https://pandoc.org/MANUAL.html#pandocs-markdown)
* [Github Flavored Markdown](https://docs.github.com/en/github/writing-on-github/)

**Comment by lervag** [comment]
By the way, a minor thing: When you show your vimrc contents, please put it inside a code block, and unless commented stuff is important somehow, please remove the commented lines.

Here's a simple example of how to type a code block with vimscript highlighting:

``````
```vim
" vimrc contents go here
set filetype plugin indent on
" ...
```
``````

**Comment by lervag** [comment]
By the way, you should also read `:help g:vim_markdown_conceal` if you did not already do. And you might want to add `set conceallevel=2` to your vimrc. This will turn on conceals for every filetype, though, unless it is disabled again by a filetype plugin. I believe this is more or less OK, but still, it is nice to be aware of it.

**Comment by EricEWeir** [comment]
> Strange. Can you report the output of the following commands after you've opened one of your notes?

> * `:verb set foldmethod`

 foldmethod=manual
> * `:verb set foldexpr`

foldexpr=0
> * `:verb set filetype`

filetype=
> * `:verb set conceallevel`

conceallevel=0
> * `:verb set concealcursor`

concealcursor=

> Also, can you do `:version` and check that the output contains `+conceal`?

Conceal is conceal+

conceallevel=0 is strange. It’s in my `.vimc` for `6`.

**Comment by EricEWeir** [comment]
> Notice that github flavored markdown is not the same as more "standard" Markdown. Further, notice that there is really no _proper_ standard for Markdown. There are a lot of flavors. These are some references I find useful that display some of the variance:
> 
> * [John Gruber's Markdown specs](https://daringfireball.net/projects/markdown/)
> * [CommonMark](http://commonmark.org/)
> * [Pandoc's Markdown](https://pandoc.org/MANUAL.html#pandocs-markdown)
> * [Github Flavored Markdown](https://docs.github.com/en/github/writing-on-github/)

I'd encountered all these but Pandoc before,  but reviewed em again. Struck me, especially while reading about github markdown, that there’s a lot that can be done zettelkasten-wise just with markdown. E.g., this:

“You can also create a Markdown hyperlink by highlighting the text and using the keyboard shortcut `Command+V`. If you'd like to replace the text with the link, use the keyboard shortcut `Command+Shift+V`.”

When I was regularly using vim and `vimwiki` on a macbook I used `multimarkdown`, though just for basic things. (`https://fletcher.github.io/MultiMarkdown-6/`) My sense is it’s geared more toward academic writing, e.g., with more attention to citing sources.

**Comment by lervag** [comment]
> > Strange. Can you report the output of the following commands after you've opened one of your notes?
> 
> > * `:verb set foldmethod`
> 
> foldmethod=manual

First: With `:verb set ...`, you should get more information about the settings, e.g. like this (for me in a `.wiki` file):

```
  foldmethod=expr
        Last set from ~/.local/plugged/wiki-ft.vim/ftplugin/wiki.vim line 14
```

The "Last set from" line will be shown when it is relevant, i.e. not always. But please, in the output I asked for, include this line if it is there.

Now, this shows that, for some reason, `foldmethod` is "manual", which is not what you want. And it brings me to another question: How do you install plugins? I notice that the plugins are not installed via your vimrc file, so you are probably relying on some other mechanism for handling/installing plugins?
> > * `:verb set filetype`
> 
> filetype=

This means that the file you are viewing does not have any filetype specified. Thus, vim-markdown is not even loaded at all. Did you show this output _after_ you opened a Markdown file from your wiki?

> conceallevel=0 is strange. It’s in my `.vimc` for `6`.

What does "`.vimrc` for `6`" mean?

**Comment by lervag** [comment]
Notice, in the vimrc file you've pasted here several times, I've never seen `set conceallevel=2`.

**Comment by lervag** [comment]
> Struck me, especially while reading about github markdown, that there’s a lot that can be done zettelkasten-wise just with markdown. E.g., this:
> 
> “You can also create a Markdown hyperlink by highlighting the text and using the keyboard shortcut `Command+V`. If you'd like to replace the text with the link, use the keyboard shortcut `Command+Shift+V`.”

Hmm. Do you mean "with the Markdown plugin" (preservim/vim-markdown)? If not, what do you mean by "just with markdown"?

**Comment by lervag** [comment]
> “You can also create a Markdown hyperlink by highlighting the text and using the keyboard shortcut `Command+V`. If you'd like to replace the text with the link, use the keyboard shortcut `Command+Shift+V`.”

Oh, you are referring to the Github flavored markdown docs ([here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links)). But that is of course only relevant when you write Markdown with the Github text editor (for comments, issues, PRs, etc).

**Comment by EricEWeir** [comment]
> > 
> > > * `:verb set foldmethod`
> > 
> > foldmethod=manual

> First: With `:verb set ...`, you should get more information about the settings…,

I didn’t have a file open when I queried those settings. Not sure this is the right way to put it, but each time the output was dumped into an empty buffer. I’ll do it over with a markdown file open.

:```
verb set foldmethod

    foldmethod=expr
	Last set from ~/.vim/pack/ivim/start/vim-markdown/after/ftplugin/markdown.vim line 182

:verb set foldexpr

  foldexpr=Foldexpr_markdown(v:lnum)
	Last set from ~/.vim/pack/ivim/start/vim-markdown/after/ftplugin/markdown.vim line 181

:verb set filetype

  filetype=markdown
	Last set from /private/var/containers/Bundle/Application/B2935018-CB04-46DE-AF7B-AFDCF699008A/iVim.app/runtime/filetype.vim line 962

:verb set conceallevel

conceallevel=0

:verb set concealcursor

  concealcursor=
```

> Now, this shows that, for some reason, `foldmethod` is "manual", which is not what you want. And it brings me to another question: How do you install plugins? I notice that the plugins are not installed via your vimrc file, so you are probably relying on some other mechanism for handling/installing plugins?

iVim has it’s own way of managing plugins called iPlug. I think it’s built on vim’s “package management” capability. It’s one of the things the developer’s done to make it possible to run a meaningful instance of vim in iOS, I think made possible by Apple’s relaxation of some of the sandboxing constraints on apps.

> > conceallevel=0 is strange. It’s in my `.vimc` for `6`.
> 
> What does "`.vimrc` for `6`" mean?

Nothing. I was confused. I was thinking of the folding level setting.

**Comment by EricEWeir** [comment]
> Notice, in the vimrc file you've pasted here several times, I've never seen `set conceallevel=2`.

Hmm. I don’t remember when I first set it. It maybe have been in my own fumbling with vim-markdown. Or this morning after I heard from you.

**Comment by EricEWeir** [comment]
> > Struck me, especially while reading about github markdown, that there’s a lot that can be done zettelkasten-wise just with markdown. E.g., this:
> > “You can also create a Markdown hyperlink by highlighting the text and using the keyboard shortcut `Command+V`. If you'd like to replace the text with the link, use the keyboard shortcut `Command+Shift+V`.”
> 
> Hmm. Do you mean "with the Markdown plugin" (preservim/vim-markdown)? If not, what do you mean by "just with markdown"?

No, I was specifically responding to what I was seeing in GitHub markdown. But I was imagining, without checking, that there would be similar capabilities, or others, with other markdown flavors.

**Comment by EricEWeir** [comment]
> > “You can also create a Markdown hyperlink by highlighting the text and using the keyboard shortcut `Command+V`. If you'd like to replace the text with the link, use the keyboard shortcut `Command+Shift+V`.”
> 
> Oh, you are referring to the Github flavored markdown docs ([here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links)). But that is of course only relevant when you write Markdown with the Github text editor (for comments, issues, PRs, etc).

I understand. I should have checked the other flavors, to see if there were similar capabilities, or others, related to my imaginings of what I’d need for zettelkasten. I’ll check out vim-markdown more carefully in this regard.

**Comment by lervag** [comment]
> `verb set foldmethod`
> ```
> foldmethod=expr
>     Last set from ~/.vim/pack/ivim/start/vim-markdown/after/ftplugin/markdown.vim line 182
> ```

> `verb set foldexpr`
> ```
> foldexpr=Foldexpr_markdown(v:lnum)
>     Last set from ~/.vim/pack/ivim/start/vim-markdown/after/ftplugin/markdown.vim line 181
> ```

It seems folding should be active and should work as expected. I don't know how this fold function works, specifically, as I don't use it. I would read the vim-markdown docs about folding to learn the details.

> `verb set conceallevel`
> ```
> conceallevel=0
> ```

This shows that `conceallevel` was never changed from the default 0. Thus, you do not have it set in your vimrc file.

> iVim has it’s own way of managing plugins called iPlug. I think it’s built on vim’s “package management” capability.

Ok. How does it _work_? What do you do, specifically, to install and/or remove a plugin?

> > > “You can also create a Markdown hyperlink by highlighting the text and using the keyboard shortcut `Command+V`. If you'd like to replace the text with the link, use the keyboard shortcut `Command+Shift+V`.”
> > 
> > Oh, you are referring to the Github flavored markdown docs ([here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links)). But that is of course only relevant when you write Markdown with the Github text editor (for comments, issues, PRs, etc).
> 
> I understand. I should have checked the other flavors, to see if there were similar capabilities, or others, related to my imaginings of what I’d need for zettelkasten. I’ll check out vim-markdown more carefully in this regard.

Ah, yes; I think you are mixing some things here. The different specifications are just that: specifications for some flavors of markdown. However, the docs for Github flavored markdown also explain how Githubs editor interface works and how you can use it to more efficiently write their Markdown flavor.

On the other hand, vim-markdown is only a plugin for Vim that is designed to help users write Markdown, and specifically, the original flavor with some extensions. See `:help vim-markdown-introduction`. And generally, it is always useful to read the docs of plugins you want to use. :)

**Comment by EricEWeir** [comment]
> It seems folding should be active and should work as expected. I don't know how this fold function works, specifically, as I don't use it. I would read the vim-markdown docs about folding to learn the details.

OK. Will do. Maybe, if needed, check with vim-markdown GitHub?

> > `verb set conceallevel`
> > ```
> > conceallevel=0
> > ```
> 
> This shows that `conceallevel` was never changed from the default 0. Thus, you do not have it set in your vimrc file.

Hmm. It’s in there. But still getting conceallevel=0.

> > iVim has it’s own way of managing plugins called iPlug. I think it’s built on vim’s “package management” capability.
> 
> Ok. How does it _work_? What do you do, specifically, to install and/or remove a plugin?

`iPlug add https://GitHub.com/preservim/vim-markdown`

Other commands are `list`, `remove`, `enable`, `disable`, `upgrade`. With them format is :iplug command pluginname. (`upgrade` does not require plugin name.)

> > > Oh, you are referring to the Github flavored markdown docs ([here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links)). But that is of course only relevant when you write Markdown with the Github text editor (for comments, issues, PRs, etc).
> > 
> > I understand. I should have checked the other flavors, to see if there were similar capabilities, or others, related to my imaginings of what I’d need for zettelkasten. I’ll check out vim-markdown more carefully in this regard.

> Ah, yes; I think you are mixing some things here. The different specifications are just that: specifications for some flavors of markdown. However, the docs for Github flavored markdown also explain how Githubs editor interface works and how you can use it to more efficiently write their Markdown flavor.

I understand.

> On the other hand, vim-markdown is only a plugin for Vim that is designed to help users write Markdown, and specifically, the original flavor with some extensions. See `:help vim-markdown-introduction`. And generally, it is always useful to read the docs of plugins you want to use. :)

For me reading is often, though not always, not enough. Usually, there are things, often lotsa things, I don’t understand. If they intrigue me I can try them, see if I can see what effect they have. (Forget understanding how they work. That’s at best a long way off, maybe never.) 

Or, if I really want it, and it’s not working, ask for help. Often it will be something simple, like a missing single-quote.

That said, thanks for the suggestion of `:help vim-markdown-introduction`

**Comment by lervag** [comment]
> > It seems folding should be active and should work as expected. I don't know how this fold function works, specifically, as I don't use it. I would read the vim-markdown docs about folding to learn the details.
> 
> OK. Will do. Maybe, if needed, check with vim-markdown GitHub?

Yes, I believe you can get better answers about vim-markdown from the devs than from me.

> > This shows that `conceallevel` was never changed from the default 0. Thus, you do not have it set in your vimrc file.
> 
> Hmm. It’s in there. But still getting conceallevel=0.

Well, I still believe you are not setting it, or that you are doing it in some erroneous way. Can you show me the line you are using? Also, if you really insist that you have `set conceallevel=2` in your vimrc, then doing `:verb set conceallevel` should show where it was changed.

> > > iVim has it’s own way of managing plugins called iPlug. I think it’s built on vim’s “package management” capability.
> > 
> > Ok. How does it _work_? What do you do, specifically, to install and/or remove a plugin?
> 
> `iPlug add https://GitHub.com/preservim/vim-markdown`

Ok. You are running this manually for each plugin? I would think you could add this to your vimrc file as well..? Also, this is clearly for Vim on iPhone or iPad, but you are not using iVim on your laptop, so how do you install plugins there?

> > On the other hand, vim-markdown is only a plugin for Vim that is designed to help users write Markdown, and specifically, the original flavor with some extensions. See `:help vim-markdown-introduction`. And generally, it is always useful to read the docs of plugins you want to use. :)
> 
> For me reading is often, though not always, not enough. Usually, there are things, often lotsa things, I don’t understand. If they intrigue me I can try them, see if I can see what effect they have. (Forget understanding how they work. That’s at best a long way off, maybe never.)
> 
> Or, if I really want it, and it’s not working, ask for help. Often it will be something simple, like a missing single-quote.
> 
> That said, thanks for the suggestion of `:help vim-markdown-introduction`

I am aware that it is sometimes less than helpful to ask people to "just read the docs". I do firmly believe that everyone can benefit from learning to read documentation and manuals, but I also acknowledge as a fact that this is a skill in its own right. For people new to Vim, for instance, it is hard to know where to even begin to read, especially if they have trouble with some plugin or addon. People like myself, who have already spent way too much time reading and learning about Vim and friends, usually have a hard time relating to the challenge it can be to learn and understand how things work.

I often tell people to slow down; I believe it is good advice. Get satisfied with something that is probably less than optimal, then try and learn something new and useful every know and then. And of course, once in a while, it is very good to spend some time to tinker with configurations. "Sharpen the axe", and all that.

**Comment by EricEWeir** [comment]
> > > This shows that `conceallevel` was never changed from the default 0. Thus, you do not have it set in your vimrc file.
> > 
> > Hmm. It’s in there. But still getting conceallevel=0.
> 
> Well, I still believe you are not setting it, or that you are doing it in some erroneous way. Can you show me the line you are using? 

`let g:vim_markdown_conceal = 2` I’ll also add in the `.vimrc` below.

> > > Ok. How does it _work_? What do you do, specifically, to install and/or remove a plugin?
> > 
> > `iPlug add https://GitHub.com/preservim/vim-markdown`
> 
> Ok. You are running this manually for each plugin? I would think you could add this to your vimrc file as well..? Also, this is clearly for Vim on iPhone or iPad, but you are not using iVim on your laptop, so how do you install plugins there?

Yes, manually for each plugin. The documentation for iPlug says nothing about putting anything in`.vimrc`. Just gives the commands to use with individual plugins. I can check to see whether there’s anything that could be put in the `.vimrc`.

iVim is vim for Apple mobile devices. I have `MacVim` on my notebook and use `vim-plug` to manage plugins.

> I am aware that it is sometimes less than helpful to ask people to "just read the docs". I do firmly believe that everyone can benefit from learning to read documentation and manuals, but I also acknowledge as a fact that this is a skill in its own right. 

I do agree that we amateurs can benefit from reading documentation and manuals. But coder/developers write for coder/developers and the language is not always easy to understand. Sometimes to the point that recommending that a noncoder-developer read the documentation is like saying, “Just try harder.” The knowledge he/she lacks is also needed to understand the documentation.

I don’t hold it against coders/developers. Especially the little guys. I’m grateful for their products. Big companies like Apple, which does a pretty good job, or Google, which isn’t quite as good, are another matter.
> 
> I often tell people to slow down; I believe it is good advice. Get satisfied with something that is probably less than optimal, then try and learn something new and useful every know and then. 

Experience—practical, hands on—the sine qua non. And patience—with ourselves and others. 

I have a just-a-friend lady friend who’s had a computer and a phone for years. She hasn’t tried anything. All she knows is Google search and Facebook, and only just the things minimally necessary for them. When she encounters a problem it’s hard for me to help her. 

The other day she sent me a form by text and asked me to print and send it back to her. She has a printer. She has rarely used it, and then only with great difficulty.

***

```
set encoding=utf-8
set fileencoding=utf-8
set fileformats=unix,dos,mac
set guifont=Menlo:h14

set wrap
set linebreak
set display=lastline
set backup

set clipboard=unnamed

set laststatus=2
set statusline=\ %F\ %r\ %l\ %c\ %y
set mousemodel=popup

set spell spelllang=en_us

let mapleader = ","

noremap <Up> gk
noremap k gk
noremap <Down> gj
noremap j gj
noremap ^ g^
noremap $ g$
inoremap jj <ESC>
nnoremap <Leader>be :%s@^\(\s*\)\(=\+\)\s\+\(.*\)\s\+\2\%(\s*\)$@\=submatch(1).

"set foldenable 
let g:vim_markdown_follow_anchor = 1
let g:vim_markdown_no_extensions_in_markdown = 1
let g:vim_markdown_new_list_item_indent = 0
let g:vim_markdown_conceal = 2
let g:vim_markdown_folding_level = 6 
let g:vim_markdown_autowrite = 1
let g:vim_markdown_strikethrough = 1

"let g:wiki_root = '~/lprivate/var/mobile/library/mobile documents/com~apple~CloudDocs/vimfiles/vimwiki/'
"let g:wiki_root = '~/vimwiki/'

let g:wiki_root = '~/private/var/mobile/library/Mobile Documents/com~apple~CloudDocs/vimfiles/wiki/'
"let g:wiki_root = '~/wiki/'
let g:wiki_filetypes = ['md']
let g:wiki_link_extension = '.md'
let g:wiki_link_target_type = 'md' 
let g:wiki_write_on_nav = 1
let g:wiki_journal = {
          \ 'date_format': {
          \   'daily' : '%y-%m-%d',
          \   'weekly' : '%y_w%V',
          \   'monthly' : '%y_m%m',
          \ },
          \}
let g:session_autoload = 'prompt'
let g:session_lock_enabled = 0

```

**Comment by lervag** [comment]
> > Well, I still believe you are not setting it, or that you are doing it in some erroneous way. Can you show me the line you are using?
> 
> `let g:vim_markdown_conceal = 2` I’ll also add in the `.vimrc` below.

Ah, no: you need `set conceallevel=2`. If it still does not work, can you again show me the output of `:verbose set conceallevel`?

I think this is actually quite well explained in the docs: `:help g:vim_markdown_conceal`:

```
To enable conceal use Vim's standard conceal configuration.

set conceallevel=2

To disable conceal regardless of 'conceallevel' setting, add the following
to your '.vimrc':

let g:vim_markdown_conceal = 0
```

Thus, you don't need to change `g:vim_markdown_conceal`. It is "enabled/true/on/1" by default and only exists to allow users to _disable_ conceals.

> > Ok. You are running this manually for each plugin? I would think you could add this to your vimrc file as well..? Also, this is clearly for Vim on iPhone or iPad, but you are not using iVim on your laptop, so how do you install plugins there?
> 
> Yes, manually for each plugin. The documentation for iPlug says nothing about putting anything in`.vimrc`. Just gives the commands to use with individual plugins. I can check to see whether there’s anything that could be put in the `.vimrc`.

Ok. It's probably OK!

> > I am aware that it is sometimes less than helpful to ask people to "just read the docs". I do firmly believe that everyone can benefit from learning to read documentation and manuals, but I also acknowledge as a fact that this is a skill in its own right.
> 
> I do agree that we amateurs can benefit from reading documentation and manuals. But coder/developers write for coder/developers and the language is not always easy to understand.

True! Or, at least, that the language is not always easy to understand. It is often assumed that the reader is familiar with various concepts.

----

I believe we should be getting close to resolving your issues now?

**Comment by EricEWeir** [comment]
> > > Well, I still believe you are not setting it, or that you are doing it in some erroneous way. Can you show me the line you are using?
> > 
> > `let g:vim_markdown_conceal = 2` I’ll also add in the `.vimrc` below.

> Ah, no: you need `set conceallevel=2`. If it still does not work, can you again show me the output of `:verbose set conceallevel`?
> 
> I think this is actually quite well explained in the docs: `:help g:vim_markdown_conceal`:
> ```
> To enable conceal use Vim's standard conceal configuration.
> 
> set conceallevel=2
> 
> To disable conceal regardless of 'conceallevel' setting, add the following
> to your '.vimrc':
> 
> let g:vim_markdown_conceal = 0
> ```
> Thus, you don't need to change `g:vim_markdown_conceal`. It is "enabled/true/on/1" by default and only exists to allow users to _disable_ conceals.

Thank you for catching this. I understood conceal was set by default. And I understood `conceallevel` needed to be set. I was confused in how I set it.

> > I do agree that we amateurs can benefit from reading documentation and manuals. But coder/developers write for coder/developers and the language is not always easy to understand.
> 
> True! Or, at least, that the language is not always easy to understand. It is often assumed that the reader is familiar with various concepts.

I don’t expect coder/developers to be more sensitive to noncoder/developers level of comprehension. It’s helpful when they are, but their priority should be doing what they’re good at—developing products that noncoder/developer’s also sometimes find helpful.

Fletcher Penney, the developer of MultiMarkdown, is a coder/developer whose prose sits easy with me.

> I believe we should be getting close to resolving your issues now?

I think so. Folding is still weird. It sorta works on the iPad: folds, but includes adjacent nonheader lines in the fold. It doesn’t work on headers on the iPhone, but does fold adjacent nonheader lines. (The `.vimrcs` are identical.) I need to get familiar with `vim-markdown`‘s folding commands.

We can close this. I have asked for help with folding and concealing on the vim-markdown github. I’ll own up to my mistake about concealing there. And reiterate my request for help with folding.

I may also check out `vim-markdown-folding`.

Thanks again for your generosity.

**Comment by lervag** [comment]
Great, glad to hear it. Feel free to open new issues/threads :)
