### ISSUE TITLE
Following and creating URL encoded links

### ISSUE THREAD

**Issue by EricEWeir** [lervag/wiki.vim#397]
A couple years ago you provided me code that, as I understand it, enables following and creating URL encoded links, saying "something like this might work." This is the code:

```
function MyTextToLink(text) abort
  return [substitute(a:text, '\s', '%20', 'g'), a:text]
endfunction

let g:wiki_resolver = 'MyLinkResolver'
function MyLinkResolver(fname, origin) abort
  let l:fname_decoded = substitute(a:fname, '%20', ' ', 'g')
  return wiki#url#wiki#resolver(l:fname_decoded, a:origin)
endfunction
```
I put the code in my .vimrc. When I click on a URL encoded link, instead of opening the linked file I get a new file with the URL encoded link as the file name.

I see there is a lot of attention to URL encoding in the wiki.vim documentation. I suspect that in it there is a way to effectively follow and create URL encoded links.

In that connection, when I posted about this issue on the Obsidian subreddit, one respondent provided code adapted from the wiki.vim documentation that enabled him "to follow URL-encoded links as if they weren't URL-encoded, and when I select some text and press Enter to create a link from it." https://www.reddit.com/r/ObsidianMD/comments/1hr6h2b/comment/m555ikt/?context=3 However he adds that ":WikiLinkAdd...doesn't apply this transformation rule."

Here is the code: 
```
function! WikiMdResolver(url) abort
    let l:url = deepcopy(a:url)

    let l:url.anchor = wiki#url#utils#extract_anchor(l:url.stripped)

    let l:path = split(l:url.stripped, '#', 1)[0]
    let l:path = wiki#url#utils#url_decode(l:path)

    let l:url.path = wiki#url#utils#resolve_path(l:path, l:url.origin)
    let l:url.stripped = l:url.path

    return l:url
endfunction

let g:wiki_link_schemes = {
            \ 'md': {
            \   'resolver': function('WikiMdResolver'),
            \ }
            \}

let g:wiki_link_creation = {
            \ 'md': {
            \   'url_transform': { x -> wiki#url#utils#url_encode(x) },
            \ },
            \}
```

However when I apply this code I get the same result that I get with the code you supplied: when I click on a link, instead of the file linked to I get a new file with the URL encoded link as the file name.

I suspect something in my .vimrc conflicts with this code. is that wiki.vim has a solution

**Comment by lervag** [comment]
> A couple years ago you provided me code that, as I understand it, enables following and creating URL encoded links, saying "something like this might work." This is the code:
> 
> ```
> function MyTextToLink(text) abort
>   return [substitute(a:text, '\s', '%20', 'g'), a:text]
> endfunction
> 
> let g:wiki_resolver = 'MyLinkResolver'
> function MyLinkResolver(fname, origin) abort
>   let l:fname_decoded = substitute(a:fname, '%20', ' ', 'g')
>   return wiki#url#wiki#resolver(l:fname_decoded, a:origin)
> endfunction
> ```

That code will not work today. wiki.vim has been changed a lot since then, and there is no longer an option called `g:wiki_resolver`. Instead, you want to change `g:wiki_link_schemes` and possibly also `g:wiki_link_creation`.

> I put the code in my .vimrc. When I click on a URL encoded link, instead of opening the linked file I get a new file with the URL encoded link as the file name.

Putting the above code in your vimrc file should have no effect (unless you are using an old version of wiki.vim).

> In that connection, when I posted about this issue on the Obsidian subreddit,

Notice that it might be better to post such issues directly on wiki.vim issue tracker. ;)

> one respondent provided code adapted from the wiki.vim documentation that enabled him "to follow URL-encoded links as if they weren't URL-encoded, and when I select some text and press Enter to create a link from it." …

The code he provides is quite good. However, you don't need to do the decoding, because that is already a part of wiki.vim by default now, see here:

https://github.com/lervag/wiki.vim/blob/80bb6dd1684a6cf13025733e4d810e36ad0ae9f3/autoload/wiki/url/resolvers.vim#L137-L141

Thus, the only thing you really want is this:

```vim
let g:wiki_link_creation = {
      \ 'md': {
      \   'url_transform': { x -> wiki#url#utils#url_encode(x) },
      \ },
      \}
```

> However he adds that ":WikiLinkAdd...doesn't apply this transformation rule."

I'm not aware of this. Don't have time to test right now, but if this is really true, then it warrants an issue and I will be glad to fix it.

> However when I apply this code I get the same result that I get with the code you supplied: when I click on a link, instead of the file linked to I get a new file with the URL encoded link as the file name.

Ok, what do you mean when you write "click on a link"? Mouse click? I'll assume you mean pressing `<cr>` to follow the link. Could you provide an example of such a link that you are trying to follow and to the file you are brought to so that I can see the resulting file name?

> I suspect something in my .vimrc conflicts with this code.

Based on our earlier communications, that would not really be surprising. But it is impossible for me to say without actually seeing your entire config.

> is that wiki.vim has a solution

?

**Comment by EricEWeir** [comment]
> > I put the code in my .vimrc. When I click on a URL encoded link, instead of opening the linked file I get a new file with the URL encoded link as the file name.
>  
> > In that connection, when I posted about this issue on the Obsidian subreddit...,
> 
> Notice that it might be better to post such issues directly on wiki.vim issue tracker. ;)

My apologies, Karl. I was unclear. I didn't post about my experience with the code you provided. I ask for experience, and hopefully help, with the general issue of accessing and creating URL encoded links from within Vim. I did so because I was conscious of my taking up more than my fair share of your time and expertise. 

> > ...one respondent provided code adapted from the wiki.vim documentation that enabled him "to follow URL-encoded links as if they weren't URL-encoded, and when I select some text and press Enter to create a link from it." …
> 
> The code he provides is quite good. However, you don't need to do the decoding, because that is already a part of wiki.vim by default now.... Thus, the only thing you really want is this:
> 
> ```viml
> let g:wiki_link_creation = {
>       \ 'md': {
>       \   'url_transform': { x -> wiki#url#utils#url_encode(x) },
>       \ },
>       \}
> ```
Thanks, for this. Haven't given it a try yet, but I certainly will be doing so soon.
> > 
> > However when I apply this code I get the same result that I get with the code you supplied: when I click on a link, instead of the file linked to I get a new file with the URL encoded link as the file name.
> 
> Ok, what do you mean when you write "click on a link"? Mouse click? I'll assume you mean pressing `<cr>` to follow the 
link. 

I meant clicking on an existing link in a note.  (Though I don't ever really click on anything; I don't even have a mouse; I use either the trackpad on my MacBook or the screen of my iPad.)

> Could you provide an example of such a link that you are trying to follow and to the file you are brought to so that I can see the resulting file name?

Here is a series of screenshots showing a file with links in my Obsidian vault open in Vim, the URL encoded link displayed, and the result of clicking on the link--an empty file with a URL encoded name.

The file with link:
 
<img width="597" alt="Screenshot 2025-01-07 at 1 49 38 PM" src="https://github.com/user-attachments/assets/3c25c2ba-ccb0-49b2-a039-b0aa646d25d5" />

URL encoded link displayed:

<img width="597" alt="Screenshot 2025-01-07 at 1 50 40 PM" src="https://github.com/user-attachments/assets/c6e32f64-a358-4999-8c43-b5a57f6e9526" />

New file with URL encoded name:

<img width="597" alt="Screenshot 2025-01-07 at 1 55 08 PM" src="https://github.com/user-attachments/assets/da4d0701-7640-485c-a369-719eb7fa948f" />

**Comment by lervag** [comment]
> > Notice that it might be better to post such issues directly on wiki.vim issue tracker. ;)
> 
> My apologies, Karl. I was unclear. I didn't post about my experience with the code you provided. I ask for experience, and hopefully help, with the general issue of accessing and creating URL encoded links from within Vim. I did so because I was conscious of my taking up more than my fair share of your time and expertise.

No problem, and I appreciate that!

> > > However when I apply this code I get the same result that I get with the code you supplied: when I click on a link, instead of the file linked to I get a new file with the URL encoded link as the file name.
> > 
> > 
> > Ok, what do you mean when you write "click on a link"? Mouse click? I'll assume you mean pressing `<cr>` to follow the
> > link.
> 
> I meant clicking on an existing link in a note. (Though I don't ever really click on anything; I don't even have a mouse; I use either the trackpad on my MacBook or the screen of my iPad.)

I don't mean to be difficult here, but "clicking" is still difficult to understand. And "a note" - is that a file opened in Vim with wiki.vim? Also, in this context, I think using the trackpad is more or less synonymous with a mouse. And similarly with touch screens.

It may seem pedantic, but I've learned the hard way that it is really important that I really understand what people are doing if I am to help them with stuff. There is a big difference between typing a key on a keyboard and pressing a mouse button.

I want to understand very explicitly what you are doing when you say you click a link. Because you use this as a context for something where you claim wiki.vim does not work as you expect.

> > Could you provide an example of such a link that you are trying to follow and to the file you are brought to so that I can see the resulting file name?
> 
> Here is a series of screenshots showing a file with links in my Obsidian vault open in Vim, the URL encoded link displayed, and the result of clicking on the link--an empty file with a URL encoded name.

Ok, thanks.

> URL encoded link displayed:

I assume you press `<cr>` with your cursor on that link to go to follow it?

> New file with URL encoded name: …

On this particular page, what does `:echo expand('%:p')` return?

I assume you added the "New file with some text." text and that you perhaps also saved the file? (I also assume it would be safe to delete that file, because it seems to not be the file you wanted.

> I opened a file with a link in my Obsidian vault:

"in my Obsidian vault" -- is that relevant? I mean, it is all just files on your system, right, it doesn't really matter where they are and if they are in your Obsidian vault?

> When I clicked on the link I got this, a new file with the encoded link as the file name:

Is that what you expect to happen?

**Comment by lervag** [comment]
I think it may be useful to take a short step back here and to describe which link behaviour is the one you expect and want to happen. And then afterwards explain what you observe with wiki.vim (preferably without changing any of the `wiki_link_...` options as a first step).

**Comment by EricEWeir** [comment]
I also tried creating a link. That went better:

<img width="667" alt="Screenshot 2025-01-07 at 2 52 45 PM" src="https://github.com/user-attachments/assets/5f8a8df5-478f-419d-bd1f-f641f8470418" />



A URL encoded link. But maybe that's what the code was intended for, i.e., not for following URL encoded links? If so, I imagine there is code for following links.

**Comment by EricEWeir** [comment]
> I think it may be useful to take a short step back here and to describe which link behaviour is the one you expect and want to happen. And then afterwards explain what you observe with wiki.vim (preferably without changing any of the `wiki_link_...` options as a first step).

I have two expectations: When I click on a URL encoded link, I am taken to the linked file. When I select some text in a file and do` <cr>` I get a URL encoded link to a file. 

I take it the `wiki_link_...` options to which you refer are `wiki_link_extension` and `wiki_link_target_type.`

What I observe with `wiki.vim` with the code for URL encoding you supplied most recently: When I click on a URL encoded link I get a new empty file with the encoded link as the filename instead of the linked file. When I select some text in a note and do `<cr>` I get a URL encoded link to a file named by the link.

As garlicbreadcleric explained it to me in my exchange with him on Reddit, `:WikiLinkAdd` opens a picker that enables you to search through already existing files to which to link. I don't understand what it was he expected but did not get regarding `:WikiLinkAdd`. I looked through the `wiki.vim` command mappings to see if there was one for `:WikiLinkAdd`. I didn't see one.

**Comment by lervag** [comment]
> I also tried creating a link. That went better: …
> 
> A URL encoded link. But maybe that's what the code was intended for, i.e., not for following URL encoded links?

Yes, exactly: `g:wiki_link_creation` is for creating links. I.e., if you select some text, it specifies how that text should transform into a link.

> If so, I imagine there is code for following links.

`g:wiki_link_schemes` is the option that controls how link url's are resolved and handled.

> > I think it may be useful to take a short step back here and to describe which link behaviour is the one you expect and want to happen. And then afterwards explain what you observe with wiki.vim (preferably without changing any of the `wiki_link_...` options as a first step).
> 
> I have two expectations: When I click on a URL encoded link, I am taken to the linked file. When I select some text in a file and do` <cr>` I get a URL encoded link to a file.

Ok, I see. But the file name itself should _not_ be URL encoded? I.e., let's say that you have a file called `my cool file.md` and a link from `index.md` to that file would then look like `[link text](my%20cool%20file.md)`?

> I take it the `wiki_link_...` options to which you refer are `wiki_link_extension` and `wiki_link_target_type.`

No, those options no longer exists. You want to set `g:wiki_link_creation` and `g:wiki_link_schemes`.

> What I observe with `wiki.vim` with the code for URL encoding you supplied most recently: When I click on a URL encoded link I get a new empty file with the encoded link as the filename instead of the linked file.

Ok; then I think the problem here is that the `g:wiki_link_schemes` is not correct. Did you change it?

Just for reference, what is your curent wiki.vim config? And for completeness: Do you have a multi-file config or do you have all of your vim config in a single file?

> When I select some text in a note and do `<cr>` I get a URL encoded link to a file named by the link.

Which is what you expect and want, right?

> As garlicbreadcleric explained it to me in my exchange with him on Reddit, `:WikiLinkAdd` opens a picker that enables you to search through already existing files to which to link. I don't understand what it was he expected but did not get regarding `:WikiLinkAdd`.

> I looked through the `wiki.vim` command mappings to see if there was one for `:WikiLinkAdd`. I didn't see one.

The default mapping is `<leader>wa`, see `:help WikiLinkAdd` and `:help wiki-mappings-default`. ;)

> > I don't mean to be difficult here, but "clicking" is still difficult to understand. And "a note" - is that a file opened in Vim with wiki.vim?....
> 
> I meant placing the cursor on the link and doing `<cr>`. By "note" I meant a file. By "opened in Vim" I meant "opened in Vim with wiki.vim Plugin installed.

Great, thanks for sharing this!

> > Is that what you expect to happen?
> 
> No. I expected the linked file to be displayed.

I believe I understand which behaviour you want now: The file names should not themselves be URL encoded, but the URLs _should_ be. Right?

**Comment by EricEWeir** [comment]
> > ... I imagine there is code for following links.
> 
> `g:wiki_link_schemes` is the option that controls how link url's are resolved and handled.

I wouldn't begin to know how to adapt what I find at `g:wiki_link_schemes` to enable following URL encoded links.

> > I have two expectations: When I click on a URL encoded link, I am taken to the linked file. When I select some text in a file and do` <cr>` I get a URL encoded link to a file.
> 
> Ok, I see. But the file name itself should _not_ be URL encoded? I.e., let's say that you have a file called `my cool file.md` and a link from `index.md` to that file would then look like `[link text](my%20cool%20file.md)`?

Yes. I guess I was unclear somewhere and got you thinking I was seeking URL encoded filenames.  What I'm seeking is what said above regarding my expectations.

> > I take it the `wiki_link_...` options to which you refer are `wiki_link_extension` and `wiki_link_target_type.`
> 
> No, those options no longer exists. You want to set `g:wiki_link_creation` and `g:wiki_link_schemes`.

I still have them in my .`vimrc`. Are they likely to interfere with getting what I want, i.e., creating and following URL encoded links? I take it I should take them out. You  have given me code for specification of `g:wiki_link_creation`.

> > What I observe with `wiki.vim` with the code for URL encoding you supplied most recently: When I click on a URL encoded link I get a new empty file with the encoded link as the filename instead of the linked file.
> 
> Ok; then I think the problem here is that the `g:wiki_link_schemes` is not correct. Did you change it?

I have nothing related to `g:wiki_link_schemes` in my `.vimrc`. Your references to it in this response is the first indication that it is needed. And as I said, I have no idea how to go about adapting what I find in the documentation on the topic to get URL link following.

> Just for reference, what is your curent wiki.vim config? And for completeness: Do you have a multi-file config or do you have all of your vim config in a single file?

This is what I have that I take to be everything related to configuring `wiki.vim`.

```
let g:wiki_root = ~/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/ZK/

let g:wiki_filetypes = ['md']
let g:wiki_link_extension = 'md'
let g:wiki_link_target_type ='.md'
let g:wiki_map_text_to_link = 'MyTextToLink'

let g:wiki_link_creation = {
      \ 'md': {
      \   'url_transform': { x -> wiki#url#utils#url_encode(x) },
      \ },
      \}

let g:wiki_write_on_nav = 1
let g:wiki_journal = {
          \ 'date_format': {
          \   'daily' : '%y-%m-%d',
          \   'weekly' : '%y_w%V',
          \   'monthly' : '%y_m%m',
          \ },
          \}

```
> > I looked through the `wiki.vim` command mappings to see if there was one for `:WikiLinkAdd`. I didn't see one.
> 
> The default mapping is `<leader>wa`, see `:help WikiLinkAdd` and `:help wiki-mappings-default`. ;)

Thanks. I will do.

> > > I don't mean to be difficult here, but "clicking" is still difficult to understand. And "a note" - is that a file opened in Vim with wiki.vim?....
> > 
> > I meant placing the cursor on the link and doing `<cr>`. By "note" I meant a file. By "opened in Vim" I meant "opened in Vim with wiki.vim Plugin installed.
> 
> Great, thanks for sharing this!
> 
> > > Is that what you expect to happen?
> > 
> > No. I expected the linked file to be displayed.
> 
> I believe I understand which behaviour you want now: The file names should not themselves be URL encoded, but the URLs _should_ be. Right?

Yes.

**Comment by lervag** [comment]
> Yes. I guess I was unclear somewhere and got you thinking I was seeking URL encoded filenames. What I'm seeking is what said above about my expectations.

Thanks, thinks are getting clearer now!

> > > I take it the `wiki_link_...` options to which you refer are `wiki_link_extension` and `wiki_link_target_type.`
> > 
> > No, those options no longer exists. You want to set `g:wiki_link_creation` and `g:wiki_link_schemes`.
> 
> I still have them in my .`vimrc`. Are they likely to interfere with getting what I want, i.e., creating and following URL encoded links?

No, they simply won't have any effect. So they're safe, but irrelevant.

> This is what I have that I take to be everything related to configuring `wiki.vim`. …

Ok thanks. As I've said before, you really _do_ need quotes around `g:wiki_root`. There is _no_ way things can work if you omit them, because it is invalid vimscript code.

For now, you could perhaps just comment that option out? I propose the following update to your config; I've basically removed deprecated options and options you didn't change from the default values:

```vim
" Comment out for now
"let g:wiki_root = ~/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/ZK/

let g:wiki_link_creation = {
      \ 'md': {
      \   'url_transform': { x -> wiki#url#utils#url_encode(x) },
      \ },
      \}

let g:wiki_journal = {
      \ 'date_format': {
      \   'daily' : '%y-%m-%d',
      \   'weekly' : '%y_w%V',
      \   'monthly' : '%y_m%m',
      \ },
      \}
```

> > `g:wiki_link_schemes` is the option that controls how link url's are resolved and handled.
> 
> I wouldn't begin to know how to adapt what I find at `g:wiki_link_schemes` to enable following URL encoded links.

Ok, I can probably help. However, I don't actually think you should need to change it at all. I've made a few updates the last months where the default for Markdown files is to apply a small amount of url encoding when creating files, and to url-decode links when following them.

So, since you want full url encoding of links when creating them, you need to set `g:wiki_link_creation` as you already do. Except for that, you really shouldn't need to change anything.

Now, we need to figure out why this isn't working for you. So, first update the config as suggested above. Then check if things work this time around. If they still don't work, then please do the following:

1. After opening one of your files in vim
2. do `:scriptnames` and copy the output here (take a screenshot if it's hard to copy)
3. describe very briefly what does still not work (e.g. "following a url-encoded link does not apply url decoding" and/or "creating a new link by selecting text and pressing `<cr>`, e.g. with the key strokes `vww<cr>`, does not apply url encoding when creating the link")

**Comment by lervag** [comment]
> I just checked: when I put quotes around `g:wiki_root` and then attempt to open a file I'm still getting: …

Yes, I remember that. But I'm still right about the fact that removing the quotes is _not_ correct. So, in the meantime, let's keep that option commented out.

> > Ok, I can probably help. However, I don't actually think you should need to change it at all. I've made a few updates the last months where the default for Markdown files is to apply a small amount of url encoding when creating files, and to url-decode links when following them.
> 
> Hmm. Surprised at the idea of URL encoded markdown.

Surprised how? Feel free to elaborate.

> And of "a small amount" of URL encoding.

Sorry, I was too lazy to be specific, which is generally a bad idea. I should have been explicit: I've added a default url encoding of paranthesis when creating links, because the parantheses are part of the link syntax itself (`[...](...)`), so if a paranthesis is part of the URL, then it _needs_ to be url encoded.

But I did not add URL encoding in _general_ when creating links, because it might be subjective if people want that or not.

> scriptnames-capture.txt

Thanks! This is useful. From this, I see that the main relevant file to inspect is `~/.vimrc`.

> What does work: selecting text and pressing `<cr>` creates a URL encoded link.

Good!

> What doesn't work: if I press `<cr>` on a URL encoded link I get a new file with the URL encoded link as the filename instead of the linked file.

This indicates that URL encoding is not applied, which either means that a) you are not using the latest version of wiki.vim, or b) you have some mis-configuration.

Next steps:

1. Can you do this in a terminal and share the output?

   ```sh
   cd ~/.vim/plugged/wiki.vim
   git show
   ```

2. Would you be willing to share your `~/.vimrc` file with me so that I can inspect your full config?

**Comment by EricEWeir** [comment]
> > I just checked: when I put quotes around `g:wiki_root` and then attempt to open a file I'm still getting: …
> 
> Yes, I remember that. But I'm still right about the fact that removing the quotes is _not_ correct. So, in the meantime, let's keep that option commented out.

My `g:wiki_root` is now quoted.
> 
> > > ... I don't actually think you should need to change it at all. I've made a few updates the last months where the default for Markdown files is to apply a small amount of url encoding when creating files, and to url-decode links when following them.
> > 
> > Hmm. Surprised at the idea of URL encoded markdown.
> 
> Surprised how? Feel free to elaborate.

The only thing  I understand clearly I understand clearly about URL encoding is that Obsidian's URL encoded links make it impossible, at least for me, to create and follow Obsidian links. I have understood Obsidian's claim to be plain text and it's URL encoded markdown links to be markdown to be stretching the truth a little. So I guess I am mistaken about that. Also, if wiki.vim's markdown links are now encoded shouldn't it be able to handle Obsidian's markdown links? Obviously I don't know what I'm talking about.  
>  
> > What doesn't work: if I press `<cr>` on a URL encoded link I get a new file with the URL encoded link as the filename instead of the linked file.
> 
> This indicates that URL encoding is not applied, which either means that a) you are not using the latest version of wiki.vim, or b) you have some mis-configuration.
> 
> Next steps:
> 
> 1. Can you do this in a terminal and share the output?
>    ```shell
>    cd ~/.vim/plugged/wiki.vim
>    git show
>    ```

```
Author: Karl Yngve Lervåg <karl.yngve+git@gmail.com>
Date:   Thu Nov 7 20:49:22 2024 +0100

    doc: fix minor issue in tag parser explanations
    
    refer: #389

diff --git a/.editorconfig b/.editorconfig
new file mode 100644
index 0000000..713f4f7
--- /dev/null
+++ b/.editorconfig
@@ -0,0 +1,10 @@
+root = true
+
+[*]
+indent_style = space
+indent_size = 2
+trim_trailing_whitespace = true
+insert_final_newline = true
+
```
> 2. Would you be willing to share your `~/.vimrc` file with me so that I can inspect your full config?

[vimrc.txt](https://github.com/user-attachments/files/18414015/vimrc.txt)

**Comment by EricEWeir** [comment]
> > > 1. Can you do this in a terminal and share the output?
> > >    ```shell
> > >    cd ~/.vim/plugged/wiki.vim
> > >    git show
> > >    ```
> > 
> > ```
> > Author: Karl Yngve Lervåg <karl.yngve+git@gmail.com>
> > Date:   Thu Nov 7 20:49:22 2024 +0100
> > 
> >     doc: fix minor issue in tag parser explanations
> >     
> >     refer: #389
> > ```
> 
> Notice the date: November 7. There's been a few updates since then, and in particular, one or more very relevant updates. Here's the log since 7th of November:
> 
> So, please update wiki.vim and try again. I believe it might resolve your problem.

When I try updating I get the following:

```
error: Your local changes to the following files would be overwritten by merge:
    	doc/wiki.txt
    Please commit your changes or stash them before you merge.
    Aborting
    Updating d84d105..80bb6dd
```
I have made no changes to `doc/wiki.txt`, except possibly by accident. But I have no idea how to "commit my changes," or to override the instruction if there's a way.

> > > 2. Would you be willing to share your `~/.vimrc` file with me so that I can inspect your full config?
> > 
> > 
> > [vimrc.txt](https://github.com/user-attachments/files/18414015/vimrc.txt)
> 
> Ok, thanks. It looks OK to me. I would probably make the following minor change to your `<leader>n` mapping:
> 
> ```viml
> nnoremap <Leader>n :e '~/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/ZK/'<CR>
> ```
> 
> `nnoremap` should be preferred unless you _want_ a recursive map. Notice the difference between `:help :map` and `:help :nore`:
> 
Thanks. Change adopted, though I can't imagine my creating a recursive remap.

**Comment by lervag** [comment]
> > Notice the date: November 7. There's been a few updates since then, and in particular, one or more very relevant updates. Here's the log since 7th of November:
> > So, please update wiki.vim and try again. I believe it might resolve your problem.
> 
> When I try updating I get the following: …
> 
> I have made no changes to `doc/wiki.txt`, except possibly by accident. But I have no idea how to "commit my changes," or to override the instruction if there's a way.

Do this:

```sh
cd ~/.vim/plugged/wiki.vim
git stash
git pull
```

> Thanks. Change adopted, though I can't imagine my creating a recursive remap.

No; as I said, it was a minor thing. ;)

**Comment by EricEWeir** [comment]
> > > So, please update wiki.vim and try again. I believe it might resolve your problem.
> > 
> > 
> > When I try updating I get the following: …
> > I have made no changes to `doc/wiki.txt`, except possibly by accident. But I have no idea how to "commit my changes," or to override the instruction if there's a way.
> 
> Do this:
> 
> ```shell
> cd ~/.vim/plugged/wiki.vim
> git stash
> git pull
> ```

Thanks. wiki.vim is now up to date.

**Comment by EricEWeir** [comment]
A little closer, but not quite there yet. When I do `<cr>` a file in the directory I get this (which I don't get if `g:wiki_root`is not quoted):

<img width="704" alt="Screenshot 2025-01-14 at 5 27 59 PM" src="https://github.com/user-attachments/assets/2d81c52b-cf0f-4fb5-b057-fc0fcd30b0a6" />

Them if I do `<cr>`on a URL encoded link I get a new file with the link decoded as the file name. (previously it was the link encoded as the file name)

**Comment by EricEWeir** [comment]
More on quoting. If this is quoted:

nnoremap <Leader>n :e '~/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/ZK/' <CR>

it takes me to `~/`  instead of to the mapped path.

**Comment by EricEWeir** [comment]
Since you said `g:wiki_link_schemes` is the code for following links, as opposed to creating them, I decided to give the following code from garlicbreadcleric a try:


```
let g:wiki_link_schemes = {
            \ 'md': {
            \   'resolver': function('WikiMdResolver'),
            \ }
            \}
```
With that in my .vimrc, when I do `<cr>` on a URL encoded linking I get the following error message. Maybe it'll be helpful in diagnosing why doing that does this instead of taking me to the linked file. 

<img width="836" alt="Screenshot 2025-01-15 at 1 31 33 PM" src="https://github.com/user-attachments/assets/c1d33376-da13-4377-b8d6-79cb9b14d0e7" />

**Comment by lervag** [comment]
> A little closer, but not quite there yet. When I do `<cr>` on a file in the directory I get this (which I don't get if `g:wiki_root` is not quoted):

"on a file" - I assume you mean on a link to a file? It's unclear, but I assume you do not mean that you are following a link here?

> Then if I do `<cr>` on a URL encoded link in the file I get a new file with the link decoded as the file name (previously it was the link encoded as the file name), instead of the linked file.

Ok, but this seems to be close to what you want. I.e., it seems the new file has the correct name, but is now in the wrong location? Is that right?

What happens if you try to follow the same link if you

1. Remove or comment out `g:wiki_root` in your vimrc?
2. Remove the quotes as you insist on?

> More on quoting. If this is quoted:
> 
> `nnoremap <Leader>n :e '~/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/ZK' <CR>`
> 
> it takes me to `~/` instead of to the mapped path.

Yes, I think you need to remove the quotes here. It should be

```vim
nnoremap <Leader>n :e ~/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/ZK<CR>
```

> Since you said `g:wiki_link_schemes` is the code for following links, as opposed to creating them, I decided to give the following code from garlicbreadcleric a try:
> 
> ```
> let g:wiki_link_schemes = {
>             \ 'md': {
>             \   'resolver': function('WikiMdResolver'),
>             \ }
>             \}
> ```

Ehm, ok. What's the definition of the `WikiMdResolver` function? It is not part of wiki.vim, so I assume you've also copied a definition of this?

> With that in my .vimrc, when I do `<cr>` on a URL encoded linking I get the following error message. Maybe it'll be helpful in diagnosing why doing that does this instead of taking me to the linked file.

Well, without knowing what the functon `WikiMdResolver` is I can't really say exactly what's wrong here. I believe the problem may be simply that you _didn't_ define that function.

That said, I don't see why this should solve any problem right now. Let's focus on the earlier threads; so please respond to my questions/requests above.

----

A couple of additional questions:

* Do you really need to keep your notes in `~/Library/Mobile Documents/iCloud~md~obsidian/Documents/ZK`? There seems to be something very strange going on with this directory, and I'm not able to figure it out.
* If you copy your notes from `~/Library/Mobile Documents/iCloud~md~obsidian/Documents/ZK` into a temporary place, e.g. `~/wiki` or `~/wikitmp`, then set `g:wiki_root` to this new place. Does that make things work as expected?

**Comment by EricEWeir** [comment]
> > ... if I do `<cr>` on a URL encoded link in the file I get a new file with the link decoded as the file name (previously it was the link encoded as the file name), instead of the linked file.
> 
> Ok, but this seems to be close to what you want. I.e., it seems the new file has the correct name, but is now in the wrong location? Is that right?

Hmm. I don't think that's right. Not literally true, but substantially true, certainly as far as the file I've been testing with in this entire thread, there is only one location, what in Obsidian speak is called the "vault," in Karl speak the folder or directory. 

The problem as I see it at this point is that the file opened is a new file, not the file linked to, and the new file, unlike the file linked to, has no content.
> 
> What happens if you try to follow the same link if you
> 
> 1. Remove or comment out `g:wiki_root` in your vimrc?

Opens a new file with the link name unencoded as the name of the file.

> 2. Remove the quotes as you insist on?> 

Ditto.

>  > Since you said `g:wiki_link_schemes` is the code for following links, as opposed to creating them, I decided to give the following code from garlicbreadcleric a try:
> > ```
> > let g:wiki_link_schemes = {
> >             \ 'md': {
> >             \   'resolver': function('WikiMdResolver'),
> >             \ }
> >             \}
> > ```
> 
> Ehm, ok. What's the definition of the `WikiMdResolver` function? It is not part of wiki.vim, so I assume you've also copied a definition of this?

Actually, I didn't copy it. But garlicbreadcleric did provide one. It seems to be an adaptation of the example you provide in `wiki-advanced-config-2`, i.e., 

```
function! WikiMdResolver(url) abort
    let l:url = deepcopy(a:url)

    let l:url.anchor = wiki#url#utils#extract_anchor(l:url.stripped)

    let l:path = split(l:url.stripped, '#', 1)[0]
    let l:path = wiki#url#utils#(l:path)

    let l:url.path = wiki#url#utils#resolve_path(l:path, l:url.origin)
    let l:url.stripped = l:url.path

    return l:url
endfunction
```

> A couple of additional questions:
> 
> * Do you really need to keep your notes in `~/Library/Mobile Documents/iCloud~md~obsidian/Documents/ZK`? There seems to be something very strange going on with this directory, and I'm not able to figure it out.

I don't need to keep them in that specific folder, but for purposes of syncing with my mobile devices I do need to keep it in a folder in the cloud. I tried the following and got the same result as reported above, i.e., a new file with the link name unencoded as the file name.

`~/Library/Mobile\ Documents/com~apple~CloudDocs/wiki`

> * If you copy your notes from `~/Library/Mobile Documents/iCloud~md~obsidian/Documents/ZK` into a temporary place, e.g. `~/wiki` or `~/wikitmp`, then set `g:wiki_root` to this new place. Does that make things work as expected?

Did as you suggested. Again, the same result as all the above, a new file with the link name unencoded as the file name, e.g.:

<img width="836" alt="Image" src="https://github.com/user-attachments/assets/60ae1425-e461-4647-8a84-7d5157da370e" />

**Comment by lervag** [comment]
> The problem as I see it at this point is that the file opened is a new file, not the file linked to, and the new file, unlike the file linked to, has no content.

This is precisely a symptom of what I tried to explain. What's the output if you open the file you want the link to open and do `:echo expand('%:p')`? Similarly, what's the output when you do the same command on the file you reach when you follow the link?

> > What happens if you try to follow the same link if you
> > 
> > 1. Remove or comment out `g:wiki_root` in your vimrc?
> 
> Opens a new file with the link name unencoded as the name of the file.
> 
> > 2. Remove the quotes as you insist on?>
> 
> Ditto.

Ok, so you say the behaviour is the same regardless of what you do with `g:wiki_root`, right?

> > > Since you said `g:wiki_link_schemes` is the code for following links, as opposed to creating them, I decided to give the following code from garlicbreadcleric a try:
> > > ```
> > > let g:wiki_link_schemes = {
> > >             \ 'md': {
> > >             \   'resolver': function('WikiMdResolver'),
> > >             \ }
> > >             \}
> > > ```
> > 
> > 
> > Ehm, ok. What's the definition of the `WikiMdResolver` function? It is not part of wiki.vim, so I assume you've also copied a definition of this?
> 
> Actually, I didn't copy it. But garlicbreadcleric did provide one. It seems to be an adaptation of the example you provide in `wiki-advanced-config-2`, i.e., …

Ok, well, the config snippet refers to a function, and if you don't provide that function it can't work. But I also strongly believe you don't need this.

----

Now, to be honest, I really don't know how to procede in helping you. I don't think there is anything wrong with wiki.vim, and it's very hard to help fix a problem that I can't reproduce on my end.

So, I'm at a loss for further ideas. Sorry!

**Comment by EricEWeir** [comment]
> > The problem as I see it at this point is that the file opened is a new file, not the file linked to, and the new file, unlike the file linked to, has no content.
> 
> This is precisely a symptom of what I tried to explain. What's the output if you open the file you want the link to open and do `:echo expand('%:p')`? Similarly, what's the output when you do the same command on the file you reach when you follow the link?

Remind me, what were you trying to explain?  

So, when I open the file I want the link to open I get this:

<img width="836" alt="Image" src="https://github.com/user-attachments/assets/b91412e9-f3c4-4195-b935-bc7b26de1761" />


And what I get on the file I reach when I follow the link is:

The same thing.

> > > What happens if you try to follow the same link if you
> > > 
> > > 1. Remove or comment out `g:wiki_root` in your vimrc?
> > 
> > 
> > Opens a new file with the link name unencoded as the name of the file.
> > > 2. Remove the quotes as you insist on?>
> > 
> > 
> > Ditto.
> 
> Ok, so you say the behaviour is the same regardless of what you do with `g:wiki_root`, right?

Yes.

> > > Ehm, ok. What's the definition of the `WikiMdResolver` function? It is not part of wiki.vim, so I assume you've also copied a definition of this?
> > 
> > Actually, I didn't copy it. But garlicbreadcleric did provide one. It seems to be an adaptation of the example you provide in `wiki-advanced-config-2`, i.e., …
> 
> Ok, well, the config snippet refers to a function, and if you don't provide that function it can't work. But I also strongly believe you don't need this.

By "this" you mean:

```
let g:wiki_link_schemes = {
            \ 'md': {
            \   'resolver': function('WikiMdResolver'),
            \ }
            \}
```
or the function?
> 
> Now, to be honest, I really don't know how to procede in helping you. I don't think there is anything wrong with wiki.vim, and it's very hard to help fix a problem that I can't reproduce on my end.
> 
> So, I'm at a loss for further ideas. Sorry!

**Comment by lervag** [comment]
> > > The problem as I see it at this point is that the file opened is a new file, not the file linked to, and the new file, unlike the file linked to, has no content.
> > 
> > 
> > This is precisely a symptom of what I tried to explain.
> 
> Remind me, what were you trying to explain?

I meant this part:

> Ok, but this seems to be close to what you want. I.e., **it seems the new file has the correct name, but is now in the wrong location**?

It seems to me that you do not have a very strong knowledge of how files and file paths and similar works? I'm not asking to be rude, just to understand if this is also a possible source of confusion and mis-communication.

> > What's the output if you open the file you want the link to open and do `:echo expand('%:p')`? Similarly, what's the output when you do the same command on the file you reach when you follow the link?
> 
> So, when I open the file I want the link to open I get this: …
> 
> And what I get on the file I reach when I follow the link is:
> 
> The same thing.

Well, that strongly indicates that you get the _same_ file as well. Right? I mean, you are saying that the file you _want_ the link to open has the exact same file name and path on your system as the file you open if you follow the link.

At the same time, you seem to insist that one of these files _has_ content, and one of them does _not_ have content. So this is a contradiction.

If the latter is true, then the file paths HAVE to be different.

----

Now, we have observed that there are strange things going on here. Perhaps what is happening is that the specific path your are working in is somehow very magic. And that it does not work in the standard "unixy" way. I have _no_ idea if this is the case, but it _would_ explain the confusing part of both this and the other threads.

> > > > Ehm, ok. What's the definition of the `WikiMdResolver` function? It is not part of wiki.vim, so I assume you've also copied a definition of this?
> > > 
> > > 
> > > Actually, I didn't copy it. But garlicbreadcleric did provide one. It seems to be an adaptation of the example you provide in `wiki-advanced-config-2`, i.e., …
> > 
> > 
> > Ok, well, the config snippet refers to a function, and if you don't provide that function it can't work. But I also strongly believe you don't need this.
> 
> By "this" you mean: …

Yes, presisely, I mean the `g:wiki_link_schemes` option.

> > Now, to be honest, I really don't know how to procede in helping you. I don't think there is anything wrong with wiki.vim, and it's very hard to help fix a problem that I can't reproduce on my end.
> > So, I'm at a loss for further ideas. Sorry!
> 
> I don't think there is anything wrong with wiki.vim either, Karl. I've tried to be careful about carry out your requests and reporting the results so that our failures to come up with a solution are not the result of my carelessness.

Thanks; I do get the impression that you are doing what I'm asking and that you are not really careless.

> The explanation could still be my carelessness, but I'm loath to go back over it all to check again. So, for now at least we'll have to leave it as that you're at a loss. But I was at a loss a long time ago, back there before my initial post on this thread.

Yes, sorry.

> All that said, I again want to express my sincere appreciation for your generosity with me--expertise- and time-wise. If I was more conversant this thread would undoubtedly have been much, much shorter. Many would have thrown me overboard long ago. And I would not have blamed them. So, again, thanks.

I'm glad you feel this way. And I'm really sorry I can't pull this through.

----

Let's do a last experiment to see if it may help shed some light on things. For this, use the last configuration that I recommended earlier for wiki.vim, i.e. this (which is still what I would recommend for now):

```vim
" Keep this commented out
"let g:wiki_root = ~/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/ZK/

let g:wiki_journal = {
      \ 'date_format': {
      \   'daily' : '%y-%m-%d',
      \   'weekly' : '%y_w%V',
      \   'monthly' : '%y_m%m',
      \ },
      \}
```

Notice how you are not really changing anything except the `g:wiki_journal`.

Now:

1. Create a new file (e.g. from Obsidian) called `~/Library/Mobile Documents/iCloud~md~obsidian/Documents/ZK/foo.md` with this content: `"Hello: [bar](bar.md)"`.

2. Confirm that the file exists and has the content by opening it with neovim and/or `cat`ing it from a terminal, e.g.

    ```sh
    cd ~/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/ZK
    cat foo.md
    ```

3. Create `~/Library/Mobile Documents/iCloud~md~obsidian/Documents/ZK/bar.md` and add some random content to it. Again, confirm that the file now exists and that you can open and view it. Open it in neovim and show the output of `:echo resolve(expand('%:p'))`.

4. Now open the `foo.md` file in neovim. Show the output of `:echo b:wiki` as well as the output of `:echo resolve(expand('%:p'))`.

5. Follow the link to `bar.md`. Again show the output of `:echo resolve(expand('%:p'))`. Did it open the file we created in step 3?

**Comment by EricEWeir** [comment]
> > Ok, but this seems to be close to what you want. I.e., **it seems the new file has the correct name, but is now in the wrong location**?
> 
> It seems to me that you do not have a very strong knowledge of how files and file paths and similar works? I'm not asking to be rude, just to understand if this is also a possible source of confusion and mis-communication.

I don't take offense at the question. But it seems to me it's for you to answer. All I can say is I haven't, to my knowledge, encountered a problem in this regard. But there is much that is a mystery to me about how even personal computers and the programs they run work. So, it's quite possible the files and file paths fall in the domain of things that are mysterious to me.

That said, and perhaps this is where lack of knowledge on my part might come into play, I will again say your interpretation  above of our latest result is not right. The problem, as I see it, is not that the new file is in the wrong location. First of all, there is only one location, a directory fundamentally with no subdirectories. Second, the problem is that the new file has no content, not the content of the file linked to.

1. This is the file with the link I want to follow, the first link:

<img width="836" alt="Image" src="https://github.com/user-attachments/assets/a4917afe-e769-45b9-a1f3-b3337fb7a40d" />

2. This the file the first link links to:

<img width="901" alt="Image" src="https://github.com/user-attachments/assets/195eb466-edee-4818-b7d0-0935aa92f356" />

3. This is the file that opens on following the link:

<img width="901" alt="Image" src="https://github.com/user-attachments/assets/a8c52906-0b3c-4a67-89c9-3ad768748f65" />

4. This is the result of doing `:echo expand('%:p')` on 2. :

<img width="901" alt="Image" src="https://github.com/user-attachments/assets/3e86547a-0ac1-4aba-b692-f480aa8dab22" />

5. This is the result of doing `:echo expand('%:p')` on 3. :

<img width="901" alt="Image" src="https://github.com/user-attachments/assets/2778616d-d8a4-42de-afb1-be6829468606" />

I just noticed that the paths are different.  4. is in `~/wiki-tmp/ZK/`.  5. is in `~/wiki-tmp/`. Checking to see what's in the latter I see that the decoded file name is a swap file:

<img width="833" alt="Image" src="https://github.com/user-attachments/assets/0d86f7fa-f246-492f-8758-13455f9c5702" />

> ... you are saying that the file you _want_ the link to open has the exact same file name and path on your system as the file you open if you follow the link.
> 
> At the same time, you seem to insist that one of these files _has_ content, and one of them does _not_ have content. So this is a contradiction.

Now we see there is no contradiction. The paths are different. The file with content is in `~/wiki-tmp/ZK/`. The empty file with the decoded name is in `~/wiki-tmp`. 

I said there is only one directory. Obviously that directory has to be in some directory. But my Obsidian files are all in one directory,  `~/wiki-temp/ZK/`. 

There is a remaining mystery. Why is the file opened on following the link outside the directory in which the linked file exists? Why is it empty? Why is it a swap file?

I have briefly reviewed the instructions for your suggested final experiment. I don't understand them, of course. I would have to just mechanically follow them and report the result. I have no problem doing that. Perhaps there will still be a point to doing so after what I report above. If so let me know. Meantime I am tired, cold and hungry.

**Comment by lervag** [comment]
> 1. This is the file with the link I want to follow, the first link:
>
> 2. This the file the first link links to:
>
> 3. This is the file that opens on following the link:
>
> 4. This is the result of doing `:echo expand('%:p')` on 2. :
>
> 5. This is the result of doing `:echo expand('%:p')` on 3. :

These were not the steps I asked you to do. But the results are enlightening. First, they show that the files are at different paths (as you also observed). This explains why things don't work as you expected.

> I said there is only one directory. Obviously that directory has to be in some directory. But my Obsidian files are all in one directory, `~/wiki-temp/ZK/`.

Yes, I believe that. But I think wiki.vim _thinks_ that `wiki-temp` is your root. This is either because you have `let g:wiki_root = '~/wiki-temp` or something similar, or because there is an `index.md` file in `~/wiki-temp`.

> There is a remaining mystery. Why is the file opened on following the link outside the directory in which the linked file exists? Why is it empty? Why is it a swap file?

This is because you never actually _saved_ the new file. The swap files are a Vim technicality, but wiki.vim won't create the files directly. Instead, the files are created when you save them.

Next step/questions:

* After opening the file `~/wiki-temp/ZK/...` (any of the files, really), what is the output of `:echo b:wiki`? And the output of `:echo g:wiki_root`?
* Do you have a file named `~/wiki-temp/index.md`?

**Comment by EricEWeir** [comment]
> > I said there is only one directory. Obviously that directory has to be in some directory. But my Obsidian files are all in one directory, `~/wiki-temp/ZK/`.
> 
> Yes, I believe that. But I think wiki.vim _thinks_ that `wiki-temp` is your root. This is either because you have `let g:wiki_root = '~/wiki-temp` or something similar, or because there is an `index.md` file in `~/wiki-temp`.

I have this: `let g:wiki_root = '~/wiki-tmp/ZK/'`. I find no `index.md` in `~/wiki-tmp` or in `'~/wiki-tmp/ZK'`.  
 
> > There is a remaining mystery. Why is the file opened on following the link outside the directory in which the linked file exists? Why is it empty? Why is it a swap file?
> 
> This is because you never actually _saved_ the new file. The swap files are a Vim technicality, but wiki.vim won't create the files directly. Instead, the files are created when you save them.

When saved the new file is empty.
>
> Next step/questions:
> 
> * After opening the file `~/wiki-temp/ZK/...` (any of the files, really), what is the output of `:echo b:wiki`? And the output of `:echo g:wiki_root`?

The output of `:echo b:wiki` is: `{'root': '/Users/ericweir/wiki-tmp/ZK', 'in_journal': 0, 'index_name': 'index', 'extension': 'md'}`

The output of `:echo g:wiki_root` is `~/wiki-tmp/ZK/

> * Do you have a file named `~/wiki-temp/index.md`?

I don't. But I think I'll create one.

**Comment by lervag** [comment]
> > > I said there is only one directory. Obviously that directory has to be in some directory. But my Obsidian files are all in one directory, `~/wiki-temp/ZK/`.
> > Yes, I believe that. But I think wiki.vim _thinks_ that `wiki-temp` is your root. This is either because you have `let g:wiki_root = '~/wiki-temp` or something similar, or because there is an `index.md` file in `~/wiki-temp`.
> 
> I have this: `let g:wiki_root = '~/wiki-tmp/ZK/'`. I find no `index.md` in `~/wiki-tmp` or in `'~/wiki-tmp/ZK'`.

Ok. And from your other answers, wiki.vim clearly understand that the root is `~/wiki-tmp/ZK`.

> > This is because you never actually _saved_ the new file. The swap files are a Vim technicality, but wiki.vim won't create the files directly. Instead, the files are created when you save them.
> 
> When saved the new file is empty.

Yes, of course; if you save an empty file it will be empty.

> > * Do you have a file named `~/wiki-temp/index.md`?
> 
> I don't. But I think I'll create one.

No, don't do that! If you want the root to be `~/wiki-temp/ZK`, then instead create the file `~/wiki-temp/ZK/index.md`.

Now, going back a few steps, you write that you have a file `~/wiki-temp/ZK/2 immediate and mediated inference.md`. It has a link in it to a file named `s 213-214 immediate and mediated inference.md`. You never showed this link - in the screenshot, I only saw the concealed version where the URL was not visible. Can you show the actual text unconcealed?

**Comment by EricEWeir** [comment]
Not an appropriate post, but I'm gonna cheat just this time. With Vimwiki I had .wiki set as markdown extent. If I change `.wiki` to `.md` on the files in my Vimwiki directory will I be able to use wiki.vim on them? I have a few years worth; it should be interesting exploring them.

**Comment by lervag** [comment]
You can use wiki.vim with `.wiki` files and `.md` files. wiki.vim does not provide syntax highlighting, but you could use https://github.com/lervag/wiki-ft.vim for that if you wanted. Still, converting to `.md` files should also just work.

**Comment by EricEWeir** [comment]
> You can use wiki.vim with `.wiki` files and `.md` files. wiki.vim does not provide syntax highlighting, but you could use https://github.com/lervag/wiki-ft.vim for that if you wanted. Still, converting to `.md` files should also just work.

Tanks.
